-- USERS

DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(32) NOT NULL,
  email VARCHAR(64) NOT NULL,
  name VARCHAR(32) DEFAULT NULL,
  avatar BLOB DEFAULT NULL
);

-- TASKS

DROP TABLE IF EXISTS tasks;

CREATE TABLE tasks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(64) NOT NULL,
    description VARCHAR(255) DEFAULT NULL,
    status CHAR(1) NOT NULL,
    priority SMALLINT NOT NULL DEFAULT 3,
    dueDate DATE DEFAULT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    userId INTEGER NOT NULL,
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_userId ON tasks(userId);
